name: Delete Stale Branches
on:
  schedule:
    # Runs every three months on the first day of the month at 12:00 UTC
    - cron: '0 9 * * *'

jobs:
  get-stale-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Git
        run: sudo apt-get install git -y
      
      - name: Get stale branches
        run: |
          ECHO='echo '
          for branch in $(git branch -a | sed 's/^\s*//' | sed 's/^remotes\///' | grep -v 'master$'); do
            if [[ "$(git log --since "April 01, 2023" $branch | wc -l)" -eq 0 ]]; then
              if [[ "$DRY_RUN" = "false" ]]; then
                ECHO=""
              fi
              local_branch_name=$(echo "$branch" | sed 's/remotes\/origin\///')
              $ECHO ${local_branch_name} >> branchesList.txt
            fi
          done
      
  delete-stale-branches:
    needs: get-stale-branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Git
        run: sudo apt-get install git -y
      
      - name: Delete stale branches
        run: |
          input="./branchesList.txt"
          while IFS= read -r line
          do
            echo "About to delete branch name :: $line" >> deletedBranches.txt
            git push origin --delete "${line}"
          done < "$input"
         env:
          GITHUB_TOKEN: ${{ secrets.PAT}}
