name: Demo removal Stale Branches
on:
  schedule:
   # - cron: "*/60 * * * *"
    - cron: "0 11 * * *"

jobs:
  delete-stale-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Git
        run: |
          sudo apt-get update
          sudo apt-get install git -y
          
      - name: Delete Stale Branches
        run: |
          set -e
          set -x
          
          git fetch
          for branch in $(git branch -a | sed 's/^\s*//' | sed 's/^remotes\///' | grep -v 'master$'); do
            if [[ "$(git log --since "April 02, 2023" $branch | wc -l)" -eq 0 ]]; then
              local_branch_name=$(echo "$branch" | sed 's/remotes\/origin\///')
              if git rev-parse --quiet --verify "origin/$local_branch_name" > /dev/null; then
                echo "Deleting branch $local_branch_name..."
                git push --delete origin "$local_branch_name" || true
              fi
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.PAT}}
