name: Testing Stale Branches
on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  delete-stale-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Git
        run: |
          sudo apt-get update
          sudo apt-get install git -y

      - name: Delete Stale Branches
        run: |
          git config --global user.email "chrlslyonga@gmail.com"
          git config --global user.name "Lyonga"
          git remote prune origin
          git fetch --all
          bash ./scripts/remove.sh
        env:
          GITHUB_TOKEN: ${{ secrets.PAT}}
