name: Archive stale branches

on:
  schedule:
    #- cron: '*/10 * * * *' 

jobs:
  delete-old-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Delete old branches
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote prune origin
          git fetch --all
          now=$(date +%s)
          for branch in $(git branch -r --no-merged); do
            if [[ $branch == origin/main* || $branch == origin/dev* || $branch == origin/prod* ]]; then
              continue
            fi
            last_commit=$(git log --format="%ct" -n 1 $branch)
            if (( now - last_commit > 30*24*60*60 )); then
              if [[ $(git log $branch) == "" ]]; then
                git push origin --delete $branch
                echo "Deleted branch $branch"
              fi
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.DEL_GITHUB_TOKEN }}
